---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jackson:
    serialization:
      fail-on-empty-beans: false

  main:
    headless: true
  sql:
    init:
      platform: postgres